post http://localhost:3000/register
Content-Type: application/json

{
    "username":"NG",
    "password":"1234567",
    "name":"Tan Le"
}

###

Post http://localhost:3000/login
Content-Type: application/json

{
    "username":"NG",
    "password":"1234567"
}

###